name: Block Fixup Commits

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  block-fixup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Block Fixup Commit Merging
        run: |
          if git log --pretty=format:%s origin/${{ github.base_ref }}..HEAD | grep -q "^fixup!"; then
            echo "Fixup commits detected. Please squash these commits before merging."
            exit 1
          fi