# This is a basic workflow to help you get started with Actions

name: MON WF

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy_job:
    runs-on: ubuntu-latest
    # The type of runner that the job will run on
    steps:

      # Steps represent a sequence of tasks that will be executed as part of the job
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Get hash of last commit and current date
        run: |
          echo "SHA=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
          echo "DATE=$(TZ=America/Montreal date +'%Y%m%dT%H%M')" >> $GITHUB_ENV

        # Runs a set of commands using the runners shell
      - name: Create Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git tag "Mon_app_$SHA_$DATE"
          git push --tags

  create_release_note_job:
    needs: deploy_job
    runs-on: ubuntu-latest
    steps:
      # Add steps to retrieve commit hashes of the last two tags starting with 'ma-deuxieme-app'
      - uses: actions/checkout@v3
      - name: Get commit hashes of last two tags for the current app
        id: get_commit_hashes
        run: |
          git fetch --tags
          TAGS=$(git tag --sort=-committerdate | grep '^Mon_app_' | head -n 2)
          FROM_TAG=$(echo "${TAGS}" | sed -n 2p)
          TO_TAG=$(echo "${TAGS}" | sed -n 1p)
          echo "FROM_TAG_HASH=$(git rev-parse "${FROM_TAG}")" >> $GITHUB_ENV
          echo "TO_TAG_HASH=$(git rev-parse "${TO_TAG}")" >> $GITHUB_ENV
          echo "FROM_TAG: ${FROM_TAG}"
          echo "TO_TAG: ${TO_TAG}"

      - name: Get commits between tags
        id: get_commits_between_tags
        run: |
          git log --pretty=format:"%h %s" $FROM_TAG_HASH..$TO_TAG_HASH > commits.txt